name = "shree-vinayaka-petrosoft"
compatibility_date = "2024-04-01"
pages_build_output_dir = "dist"

[vars]
STATION_NAME = "SHREE VINAYAKA PETROSOFT FUEL JUNCTION"
RO_CODE = "IOCL-RO-849201"
ENVIRONMENT = "production"
